### ISSUE TITLE
Implement Random Quote Generation

### ISSUE THREAD

**Issue by arishuynhvan** [Bigghead/Momentum-Clone#8]

**Comment by djmousefarm** [comment]
I don't know if anyone else has done or attempted the Random Quote generator in FCC or not but an issue i faced was in determining a suitable API for quote generation.  I tried several but found them either impenetrable (wikiquote) or frustratingly gated behind soft paywalls.  Other than that they were just quite silly (Chuck Norris "quote" generator).  In the end I made my own list of quotes in a json file i hosted in dropbox.  Any thoughts from anyone else?  Anyone found a better choice of quote API?

**Comment by Bigghead** [comment]
I used Forismatic, which worked pretty well
